### ISSUE TITLE
base lpc device documentation

### ISSUE THREAD

**Issue by gregjhansell97** [zackpi/lpc-serial#1]
correct comments on all functions, currently copy pasta'd a template for every function

**Comment by gregjhansell97** [comment]
when a function is done, leave a page number as a comment above pass

**Comment by gregjhansell97** [comment]
here's the style guide I'm sort of following: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by gregjhansell97** [comment]
the reason for the style guide is we can then use Sphinx to auto build api documentation for us

**Comment by zackpi** [comment]
nice, I'll read up on it before making any new changes
